'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Search,Camera,Plus,Library,Globe,ArrowUpRight,SlidersHorizontal,Package,ImageIcon,ChevronRight,Loader2,AlertCircle,RefreshCw,X,Check,PanelLeftClose,Archive,HardDrive} from 'lucide-react';
import {Sidebar,SidebarProvider,SidebarContent,SidebarHeader,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton} from '@/components/ui/sidebar';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Toaster,toast} from 'sonner';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {type Product,CONDITIONS,CONDITION_LABELS,STATUS_LABELS,money,missingFields,blankProduct,officialFor} from '@/lib/domain';
import ProductEditor from './product-editor';
import ProductDetail from './product-detail';
import PhotoSearch from './photo-search';
import Finder from './finder';
import BackupPanel from './backup-panel';
import {catalogRequest as fetch,resolvePhoto} from '@/lib/local-catalog';
export function Photo({src,alt,className=''}:{src?:string;alt:string;className?:string}){const [url,setUrl]=useState(''),[failed,setFailed]=useState(false);useEffect(()=>{let live=true;setUrl('');setFailed(false);if(src)resolvePhoto(src).then(value=>{if(live)setUrl(value);}).catch(()=>{if(live)setFailed(true);});return()=>{live=false;};},[src]);return url&&!failed?<img className={className} src={url} alt={alt} loading="lazy" onError={()=>setFailed(true)}/>:<div className={'photo-placeholder '+className}><ImageIcon size={36}/><span>{src&&!failed?'读取照片…':'待添加照片'}</span></div>;}
export function Picker({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="picker"><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i.value} value={i.value}>{i.label}</SelectItem>)}</SelectContent></Select>;}
export default function CatalogApp(){
 const [products,setProducts]=useState<Product[]>([]),[samples,setSamples]=useState<Product[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [view,setView]=useState('library'),[q,setQ]=useState(''),[category,setCategory]=useState('all'),[status,setStatus]=useState('all'),[condition,setCondition]=useState('all');
 const [editor,setEditor]=useState<Product|null>(null),[detail,setDetail]=useState<Product|null>(null),[camera,setCamera]=useState(false),[settings,setSettings]=useState(false),[days,setDays]=useState(90),[showCombined,setShowCombined]=useState(true),[preview,setPreview]=useState(false);
 const [backup,setBackup]=useState(false),[extraFilters,setExtraFilters]=useState(false);
 const searchRef=useRef<HTMLInputElement>(null);
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/products');const d=await r.json() as {products:Product[];error?:string};if(!r.ok)throw Error(d.error);setProducts(d.products);}catch(e){setError(e instanceof Error?e.message:'无法加载资料库');}finally{setLoading(false);}}
 useEffect(()=>{load();fetch('/api/samples').then(r=>r.ok?r.json() as Promise<Product[]>:[]).then(setSamples).catch(()=>{});const raw=localStorage.getItem('jellyshelf:preferences');if(raw)try{const s=JSON.parse(raw);if([30,90,180,365].includes(s.days))setDays(s.days);setShowCombined(s.combined!==false);}catch{}},[]);
 useEffect(()=>{function key(e:KeyboardEvent){if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();searchRef.current?.focus();}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const source=preview?samples:products;
 const filtered=useMemo(()=>source.filter(p=>{const text=[p.nameZh,p.nameEn,...p.variants.flatMap(v=>[v.sku,v.size])].join(' ').normalize('NFKC').toLowerCase();return q.trim().toLowerCase().split(/\s+/).every(t=>text.includes(t))&&(category==='all'||p.category===category)&&(status==='all'||(status==='unknown'?p.variants.some(v=>!officialFor(p,v).officialStatus):p.variants.some(v=>officialFor(p,v).officialStatus===status)))&&(condition==='all'||p.variants.some(v=>v.condition===condition));}),[source,q,category,status,condition]);
 async function saved(p:Product){setProducts(prev=>[p,...prev.filter(x=>x.id!==p.id)]);setEditor(null);setDetail(p);setPreview(false);toast.success('已保存到我的资料库');}
 function importSample(p:Product){setDetail(null);setEditor({...p,id:crypto.randomUUID(),revision:0,variants:p.variants.map(v=>({...v,id:crypto.randomUUID()}))});}
 const nav=[{id:'library',label:'我的资料库',icon:Library},{id:'finder',label:'联网找货',icon:Globe}];
 return <SidebarProvider className="cream-app"><Sidebar className="main-sidebar"><SidebarHeader className="brand"><div className="soft-flower" aria-hidden="true"><i/><i/><i/><i/></div><div><strong>JellyShelf</strong><small>THE SOFT ARCHIVE</small></div></SidebarHeader><SidebarContent><div className="nav-caption">工作空间</div><SidebarMenu>{nav.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={view===n.id} onClick={()=>setView(n.id)} className="nav-item"><n.icon size={19}/><span>{n.label}</span>{n.id==='library'&&<b>{products.length}</b>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="sidebar-note"><Camera size={23}/><strong>眼前这只，一拍就找</strong><p>从你的资料库里寻找相似商品。</p><Button variant="outline" onClick={()=>setCamera(true)}>拍照查货 <ArrowUpRight size={16}/></Button></div></SidebarContent><SidebarFooter><div className="private-label"><span className="avatar">私</span><div><strong>本机工作空间</strong><small>资料仅保存在当前浏览器</small></div></div></SidebarFooter></Sidebar>
 <main className="workspace"><header className="topbar"><div className="mobile-brand"><span className="soft-flower" aria-hidden="true"><i/><i/><i/><i/></span><div><strong>JellyShelf</strong><small>THE SOFT ARCHIVE</small></div></div><div className="breadcrumb">工作空间 <ChevronRight size={14}/> <span>{view==='library'?'我的资料库':'联网找货'}</span></div><div className="topbar-end"><span className="private-badge"><HardDrive size={12}/>本机保存</span><button className="icon-btn" onClick={()=>setBackup(true)} aria-label="数据与备份"><Archive size={20}/></button><button className="icon-btn mobile-add" onClick={()=>setEditor(blankProduct())} aria-label="录入商品"><Plus size={22}/></button><button className="icon-btn" onClick={()=>setSettings(true)} aria-label="行情统计设置"><SlidersHorizontal size={19}/></button></div></header>
 <div className={"page-body "+(q||category!=="all"||status!=="all"||condition!=="all"?"is-searching":"")}>{view==='finder'?<Finder onDraft={p=>setEditor(p)} samples={samples}/>:<><div className="page-heading"><div><div className="eyebrow">LITTLE THINGS, BIG LOVE.</div><h1>我的软软收藏<span className="heading-dot">.</span></h1><p>收好每一只，查找更从容。</p></div><div className="collection-count"><strong>{products.length.toString().padStart(2,'0')}</strong><span>款已收录</span></div><div className="heading-actions"><Button variant="outline" className="camera-button" onClick={()=>setCamera(true)}><Camera size={18}/>拍照查货</Button><Button className="primary-button" onClick={()=>setEditor(blankProduct())}><Plus size={18}/>录入商品</Button></div></div>
 <div className="library-summary"><div><span className="stat-value">{products.length.toString().padStart(2,'0')}</span><span>已收录商品</span></div><div><span className="stat-value">{products.reduce((n,p)=>n+p.variants.length,0).toString().padStart(2,'0')}</span><span>尺寸 / 品相分支</span></div><div><span className="stat-value warning-value">{products.filter(p=>missingFields(p).length).length.toString().padStart(2,'0')}</span><span>资料待补充</span></div><div className="summary-note"><span>直播查货</span><strong>输入品名，或者拍一张照片</strong></div></div>
 <section className="catalog-surface"><div className="search-row"><div className="search-box"><Search size={20}/><Input ref={searchRef} value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索中文名、英文名或官方货号…" aria-label="搜索商品"/>{q?<button onClick={()=>setQ('')} aria-label="清空搜索"><X size={16}/></button>:<kbd>⌘ K</kbd>}</div><button className="quick-camera" onClick={()=>setCamera(true)} aria-label="拍照查货"><Camera size={23}/></button></div><div className="advanced-filters" hidden={!extraFilters}><Picker label="品相筛选" value={condition} onChange={setCondition} items={[{value:'all',label:'全部品相'},...CONDITIONS.map(c=>({value:c,label:c+' '+CONDITION_LABELS[c]}))]}/><Picker label="官方状态筛选" value={status} onChange={setStatus} items={[{value:'all',label:'全部官方状态'},...Object.entries(STATUS_LABELS).map(([value,label])=>({value,label})),{value:'unknown',label:'状态待确认'}]}/></div><div className="catalog-toolbar"><Tabs value={category} onValueChange={setCategory}><TabsList variant="line">{[{v:'all',n:'全部商品'},{v:'公仔',n:'公仔'},{v:'挂件',n:'挂件'},{v:'其他',n:'其他'}].map(t=><TabsTrigger key={t.v} value={t.v}>{t.n}</TabsTrigger>)}</TabsList></Tabs><button className={'filter-toggle '+(extraFilters||status!=='all'||condition!=='all'?'filter-active':'')} onClick={()=>setExtraFilters(!extraFilters)} aria-expanded={extraFilters} aria-label="展开品相和官方状态筛选"><SlidersHorizontal size={17}/><span>筛选</span></button></div>
 {preview&&<div className="preview-banner"><span>官网参考样例 · 尚未存入你的资料库，首发价等未知信息留白</span><button onClick={()=>setPreview(false)}>返回我的资料库 <X size={14}/></button></div>}
 {error?<div className="empty-state"><AlertCircle/><h2>暂时无法读取资料库</h2><p>{error}</p><Button variant="outline" onClick={load}><RefreshCw size={16}/>重新加载</Button></div>:loading?<div className="empty-state"><Loader2 className="spin"/><p>正在打开资料库…</p></div>:filtered.length?<><div className="collection-section-heading"><h2>{q?'找到的收藏':preview?'官网参考样例':'收藏手记'}</h2><span>{filtered.length} 款 · {preview?'尚未录入':'我的资料'}</span></div><div className={'product-grid '+(!q&&category==='all'&&status==='all'&&condition==='all'?'featured-grid':'')}>{filtered.map((p,i)=><ProductTile key={p.id} product={p} featured={i===0&&!q&&category==='all'&&status==='all'&&condition==='all'} onOpen={()=>setDetail(p)}/>)}</div></>:<div className="empty-state"><div className="empty-icon"><Package size={32}/></div><h2>{products.length||q?'没有找到匹配的商品':'从第一只 Jellycat 开始'}</h2><p>{products.length||q?'试试英文名的一部分，或调整筛选条件。':'录入名称、照片和货号，下一次直播就能快速找到它。'}</p><Button className="primary-button" onClick={()=>setEditor(blankProduct())}><Plus size={17}/>录入第一款商品</Button><button className="text-button import-empty" onClick={()=>setBackup(true)}><Archive size={15}/>从备份恢复资料</button>{samples.length>0&&<button className="text-button" onClick={()=>{setPreview(true);setQ('');setCategory('all');setCondition('all');setStatus('all');}}>用官网样例试试看 <ArrowUpRight size={15}/></button>}</div>}
 </section><div className="page-foot"><span>JELLYSHELF / 本机商品资料库</span><span>资料存在当前浏览器，录入后记得导出备份。</span></div></> }</div>
 </main><nav className="mobile-nav" aria-label="主要导航"><button className={view==='library'?'active':''} onClick={()=>setView('library')}><Library size={21}/>资料库</button><button onClick={()=>setCamera(true)}><Camera size={23}/>拍照查货</button><button className={view==='finder'?'active':''} onClick={()=>setView('finder')}><Globe size={21}/>联网找货</button><button onClick={()=>setEditor(blankProduct())}><Plus size={23}/>新增</button></nav>
 {editor&&<ProductEditor product={editor} onClose={()=>setEditor(null)} onSaved={saved}/>}
 {detail&&<ProductDetail product={detail} days={days} combined={showCombined} isSample={preview} onClose={()=>setDetail(null)} onEdit={()=>{if(preview)importSample(detail);else{setEditor(detail);setDetail(null);}}} onDeleted={()=>{setProducts(p=>p.filter(x=>x.id!==detail.id));setDetail(null);}} onSaved={p=>{setProducts(old=>old.map(x=>x.id===p.id?p:x));setDetail(p);}}/>}
 <PhotoSearch open={camera} onClose={()=>setCamera(false)} products={products} onSelect={p=>{setDetail(p);setCamera(false);setPreview(false);}}/>
 <BackupPanel open={backup} onClose={()=>setBackup(false)} onRestored={()=>{setPreview(false);setDetail(null);load();}}/>
 <Dialog open={settings} onOpenChange={setSettings}><DialogContent><DialogTitle>行情统计设置</DialogTitle><DialogDescription>仅统计同货号、同尺寸、同品相的美国美元单件成交，价格不含运费和税。</DialogDescription><label className="field-label">成交时间范围</label><Picker label="成交时间范围" value={String(days)} onChange={v=>{setDays(+v);localStorage.setItem('jellyshelf:preferences',JSON.stringify({days:+v,combined:showCombined}));}} items={[30,90,180,365].map(d=>({value:String(d),label:'最近 '+d+' 天'}))}/><label className="field-label">建议价展示</label><Picker label="建议价展示" value={showCombined?'combined':'separate'} onChange={v=>{setShowCombined(v==='combined');localStorage.setItem('jellyshelf:preferences',JSON.stringify({days,combined:v==='combined'}));}} items={[{value:'combined',label:'分别展示，并计算综合中位数'},{value:'separate',label:'仅分别展示两个平台'}]}/><p className="muted small-text">少于 5 笔合格成交时提示参考不足；无合格记录时留白。设置只保存在本设备。</p></DialogContent></Dialog><Toaster richColors position="top-center"/></SidebarProvider>;
}

function compactPrice(p:Product){const v=p.variants[0];if(v.targetLow===null||v.targetHigh===null)return '待填写';const fmt=(n:number)=>n.toLocaleString('en-US',{minimumFractionDigits:Number.isInteger(n)?0:2,maximumFractionDigits:2});return '$'+fmt(v.targetLow)+'–'+fmt(v.targetHigh);}
function ProductTile({product:p,featured,onOpen}:{product:Product;featured:boolean;onOpen:()=>void}){const v=p.variants[0];const official=officialFor(p,v);return <button className={'product-card '+(featured?'featured-product':'')} onClick={onOpen}><div className="card-photo"><Photo src={p.photos[0]} alt={p.nameZh||p.nameEn}/><span className="category-tag">{p.category}</span>{!featured&&<span className="card-condition">{v.condition||'品相待填'}</span>}<div className="card-open"><ArrowUpRight size={18}/></div></div><div className="card-copy">{featured&&<span className="featured-kicker">A SOFT SPOT<br/><b>FOR YOUR FAVORITES</b></span>}<div className="card-sku">{v.sku||'货号待补充'}</div><h2>{p.nameZh||p.nameEn}</h2>{p.nameZh&&<p>{p.nameEn}</p>}<div className="card-variants"><span>{v.condition||'品相待确认'}</span><span>{v.size||'尺寸待补充'}</span></div><div className="card-price"><span>{p.variants.length>1?'首个分支目标价':'目标成交价'}</span><strong>{compactPrice(p)}</strong></div>{p.variants.length>1&&<div className="card-branch-note">{p.variants.length} 个尺寸 / 品相分支 · 点开选择</div>}{!featured&&<div className={'card-status '+(!official.officialStatus?'unknown':'')}>{STATUS_LABELS[official.officialStatus]||'官方状态待核实'}</div>}</div></button>;}
