'use client';
import {catalogRequest as fetch} from '@/lib/local-catalog';
import {useState} from 'react';
import {Search,ArrowUpRight,ExternalLink,Plus,Loader2,Info,Globe} from 'lucide-react';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {type Product,blankProduct} from '@/lib/domain';
import {Photo} from './catalog-app';
export default function Finder({onDraft,samples}:{onDraft:(p:Product)=>void;samples:Product[]}){
 const [query,setQuery]=useState(''),[busy,setBusy]=useState(false),[results,setResults]=useState<Product[]>([]),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const encoded=encodeURIComponent(query.trim()||'Jellycat');
 async function search(e:React.FormEvent){e.preventDefault();setBusy(true);setResults([]);setError('');setNotice('');try{const r=await fetch('/api/lookup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query})});const d=await r.json() as {candidates:Product[];notice:string;error?:string};if(!r.ok)throw Error(d.error);setResults(d.candidates);setNotice(d.notice);}catch(e){setError(e instanceof Error?e.message:'查找未完成，请稍后重试。');}finally{setBusy(false);}}
 function draft(p:Product){onDraft({...p,id:crypto.randomUUID(),revision:0,variants:p.variants.map(v=>({...v,id:crypto.randomUUID()}))});}
 return <><div className="page-heading"><div><div className="eyebrow">DISCOVER & COLLECT</div><h1>联网找货<span className="heading-dot">.</span></h1><p>核对官方资料，把新发现收进自己的资料库。</p></div></div><form className="finder-search" onSubmit={search}><h2>从品名或官方链接开始</h2><p>名称与货号先匹配已核实参考资料；本机版的官网链接请打开原页核对。</p><div className="finder-input"><Input aria-label="联网查找内容" value={query} onChange={e=>setQuery(e.target.value)} placeholder="英文品名、官方货号，或美国官网商品链接" required/><Button className="primary-button" disabled={busy}>{busy?<Loader2 size={17} className="spin"/>:<Search size={17}/>}查找资料</Button></div><div className="finder-links"><a href={'https://us.jellycat.com/search.php?search_query='+encoded} target="_blank" rel="noreferrer">美国官网 <ArrowUpRight size={14}/></a><a href={'https://www.ebay.com/sch/i.html?_nkw='+encoded+'&LH_Sold=1&LH_Complete=1'} target="_blank" rel="noreferrer">eBay 已售记录 <ArrowUpRight size={14}/></a><a href="https://www.whatnot.com/" target="_blank" rel="noreferrer">打开 Whatnot <ArrowUpRight size={14}/></a></div></form>{notice&&<div className="integration-note"><Info size={18}/><span>{notice}</span></div>}{error&&<div className="form-error" role="alert" style={{marginTop:20}}>{error}</div>}{results.map(p=><article key={p.id} className="finder-result"><div className="finder-result-top"><Photo src={p.photos[0]} alt={p.nameEn}/><div><h3>{p.nameZh||p.nameEn}</h3><p>{p.nameEn}<br/>{p.variants[0]?.sku} · {p.variants[0]?.size||'尺寸待核实'}</p><Button className="primary-button" onClick={()=>draft(p)}><Plus size={16}/>核对并录入</Button></div></div><p style={{marginTop:15}}>{p.notes}</p><a className="detail-source" href={p.sourceUrl} target="_blank" rel="noreferrer">核对官网来源 <ExternalLink size={13}/></a></article>)}
 <div className="finder-section-title"><h2>官网参考样例</h2><span>未存入资料库 · 2026-09-27 核对</span></div><div className="reference-grid">{samples.map(p=><button className="reference-card" key={p.id} onClick={()=>draft(p)}><Photo src={p.photos[0]} alt={p.nameEn}/><strong>{p.nameZh||p.nameEn}</strong><small>{p.variants[0]?.sku} <ArrowUpRight size={12} style={{display:'inline'}}/></small></button>)}</div><div className="integration-note"><Globe size={19}/><div>陌生新款的联网图片识别尚未接入。库内拍照查货可直接使用；全网自动识别与历史成交自动采集需要另外接通数据服务。<br/><button className="text-button" style={{paddingLeft:0}} onClick={()=>onDraft(blankProduct())}>先手动录入一款 <Plus size={14}/></button></div></div></>;
}
