'use client';
import {resolvePhoto} from '@/lib/local-catalog';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Progress} from '@/components/ui/progress';
import {Camera,Upload,Loader2,ChevronRight} from 'lucide-react';
import type {Product} from '@/lib/domain';
import {Photo} from './catalog-app';
export default function PhotoSearch({open,onClose,products,onSelect,demo=false}:{open:boolean;onClose:()=>void;products:Product[];onSelect:(p:Product)=>void;demo?:boolean}){
 const [query,setQuery]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[message,setMessage]=useState(''),[error,setError]=useState(''),[results,setResults]=useState<{product:Product;score:number}[]>([]);const job=useRef(0);
 useEffect(()=>()=>{job.current++;},[]);useEffect(()=>{if(!open)job.current++;},[open]);useEffect(()=>()=>{if(query)URL.revokeObjectURL(query);},[query]);
 async function search(file:File|undefined){if(!file)return;if(file.size>12*1024*1024||!file.type.startsWith('image/')){setError('请选择 12 MB 以内的图片。');return;}const current=++job.current;const url=URL.createObjectURL(file);setQuery(url);setResults([]);setBusy(true);setError('');setMessage('正在准备本机图片识别，首次使用需要加载模型…');setProgress(0);
 try{const {embedPhoto,cosine}=await import('@/lib/vision');const vector=await embedPhoto(url);const candidates=products.filter(p=>p.photos.length);const found:{product:Product;score:number}[]=[];let failures=0;for(let i=0;i<candidates.length;i++){if(job.current!==current)return;const p=candidates[i];setMessage('正在比对 '+(i+1)+' / '+candidates.length+' 款商品…');let best=-1;for(const src of p.photos){try{const path=await resolvePhoto(src);const v=await embedPhoto(path,true);best=Math.max(best,cosine(vector,v));}catch{failures++;}}if(best>=0)found.push({product:p,score:best});setProgress(Math.round((i+1)/candidates.length*100));await new Promise(r=>setTimeout(r,0));}if(job.current!==current)return;setResults(found.sort((a,b)=>b.score-a.score).slice(0,5));setMessage(found.length?'以下为外观相似候选，请核对货号和尺寸。':'没有可比对的照片，请先为商品添加照片。');if(failures)setError(failures+' 张资料库照片无法加载，已跳过。');}
 catch(e){if(job.current===current)setError(e instanceof Error?e.message:'图片识别未完成，请重试。');}finally{if(job.current===current)setBusy(false);}}
 return <Dialog open={open} onOpenChange={o=>{if(!o){job.current++;setBusy(false);onClose();}}}><DialogContent className="screen-dialog"><div className="eyebrow">VISUAL SEARCH</div><DialogTitle>拍一下，找库里的这只</DialogTitle><DialogDescription>{demo?'照片在本机比对，仅检索演示图册里的商品；相似款式和尺寸需要你确认。':'照片在本机比对，只检索已录入商品。相似款式与尺寸需要你确认。'}</DialogDescription>{query&&<img src={query} alt="待识别的商品照片" className="photo-query-preview"/>}<div className="upload-strip" style={{justifyContent:'center'}}><label className="upload-box"><Camera/><span>拍摄实物</span><input type="file" accept="image/*" capture="environment" disabled={busy||!products.length} onChange={e=>search(e.target.files?.[0])}/></label><label className="upload-box"><Upload/><span>从相册选择</span><input type="file" accept="image/*" disabled={busy||!products.length} onChange={e=>search(e.target.files?.[0])}/></label></div>{!products.length&&<p className="missing-strip">资料库还没有商品。先录入名称与照片，即可使用拍照查货。</p>}{busy&&<Progress value={progress}/>}<p role="status" className="detail-note">{message}</p>{error&&<p className="form-error" role="alert">{error}</p>}<div className="photo-results">{results.map(r=><button key={r.product.id} className="photo-result" onClick={()=>onSelect(r.product)}><Photo src={r.product.photos[0]} alt={r.product.nameEn}/><div><strong>{r.product.nameZh||r.product.nameEn}</strong><p>{r.product.variants[0]?.sku} · 相似度 {r.score.toFixed(2)}</p></div><ChevronRight size={17}/></button>)}</div>{results.length>0&&<p className="detail-note">相似度只用于排序，不代表识别正确率；照片不能可靠判断实物尺寸或品相。</p>}</DialogContent></Dialog>;
}
