'use client';
import {catalogRequest as fetch} from '@/lib/local-catalog';
import {useRef,useState} from 'react';
import {useForm,useFieldArray,Controller} from 'react-hook-form';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Plus,Upload,Trash2,Loader2,Save,X,Info,ImageIcon,Camera} from 'lucide-react';
import {toast} from 'sonner';
import {type Product,type SkuEdit,blankVariant,CONDITIONS,CONDITION_LABELS,STATUS_LABELS,costRange,money,validateProduct,normalizeProduct,beginSkuEdit,commitSkuEdit} from '@/lib/domain';
import {Photo,Picker} from './catalog-app';
import {isNativeApp,pickNativePhoto} from '@/lib/platform';
export default function ProductEditor({product,onClose,onSaved}:{product:Product;onClose:()=>void;onSaved:(p:Product)=>void}){
 const {register,control,handleSubmit,watch,setValue,getValues,formState:{isDirty}}=useForm<Product>({defaultValues:normalizeProduct(product)});
 const {fields,append,remove}=useFieldArray({control,name:'variants'});
 const [saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState('');
 const skuEdit=useRef<SkuEdit|undefined>(undefined);
 const photos=watch('photos'),variants=watch('variants');
 function writeOfficialFacts(next:Product){next.variants.forEach((v,i)=>{setValue(`variants.${i}.releaseDate`,v.releaseDate,{shouldDirty:true});setValue(`variants.${i}.releasePrice`,v.releasePrice,{shouldDirty:true});setValue(`variants.${i}.officialStatus`,v.officialStatus,{shouldDirty:true});setValue(`variants.${i}.sourceUrl`,v.sourceUrl,{shouldDirty:true});});}
 function commitSkuEditing(raw=getValues()){const edit=skuEdit.current;skuEdit.current=undefined;const next=commitSkuEdit(raw,edit);writeOfficialFacts(next);return next;}
 function beginSkuEditing(index:number){const id=getValues(`variants.${index}.id`);if(skuEdit.current?.variantId===id)return;if(skuEdit.current)commitSkuEditing();skuEdit.current=beginSkuEdit(getValues(),id);}
 function removeBranch(index:number){commitSkuEditing();remove(index);}
 async function upload(files:FileList|File[]|null){if(!files)return;setUploading(true);setError('');try{const urls=[...photos];for(const file of Array.from(files).slice(0,12-urls.length)){const form=new FormData();form.append('file',file);const r=await fetch('/api/photos',{method:'POST',body:form});const d=await r.json() as {url:string;error?:string};if(!r.ok)throw Error(d.error);urls.push(d.url);setValue('photos',[...urls],{shouldDirty:true});}toast.success('照片已添加到本机');}catch(e){setError(e instanceof Error?e.message:'照片上传失败');}finally{setUploading(false);}}
 async function chooseNativePhoto(source:'camera'|'photos'){setUploading(true);setError('');try{const file=await pickNativePhoto(source);if(file)await upload([file]);}catch(e){setError(e instanceof Error?e.message:'无法读取照片，请重试。');}finally{setUploading(false);}}
 async function save(raw:Product){const p=commitSkuEditing(raw);setError('');const errors=validateProduct(p);if(errors.length){setError(errors.join('；'));return;}setSaving(true);try{const r=await fetch('/api/products'+(p.revision?'/'+p.id:''),{method:p.revision?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const d=await r.json() as {product:Product;error?:string};if(!r.ok)throw Error(d.error);onSaved(d.product);}catch(e){setError(e instanceof Error?e.message:'保存失败');}finally{setSaving(false);}}
 function numeric(name:'releasePrice'|`variants.${number}.purchasePrice`|`variants.${number}.targetLow`|`variants.${number}.targetHigh`|`variants.${number}.releasePrice`,label:string){return <label className="form-field"><span>{label}</span><Controller name={name} control={control} render={({field})=><div className="money-input"><span>$</span><Input aria-label={label} inputMode="decimal" type="number" step="0.01" min="0" value={field.value??''} onChange={e=>field.onChange(e.target.value===''?null:Number(e.target.value))}/></div>}/></label>;}
 return <Dialog open onOpenChange={open=>{if(!open&&!saving&&!uploading){if(!isDirty||window.confirm('未保存的修改将丢失，确定关闭吗？'))onClose();}}}><DialogContent className="editor-dialog"><div className="editor-head"><div className="eyebrow">COLLECTION EDITOR</div><DialogTitle>{product.revision?'编辑商品资料':'录入一款商品'}</DialogTitle><DialogDescription>填入已确认的信息。不确定的内容可以留空，保存前请核对。</DialogDescription></div><form onSubmit={handleSubmit(save)} className="editor-form"><div className="editor-scroll"><fieldset disabled={saving||uploading}><section className="form-section"><h3><span>01</span>商品照片</h3><div className="upload-strip">{photos.map((p,i)=><div className="upload-thumb" key={p}><Photo src={p} alt={'商品照片 '+(i+1)}/><button type="button" aria-label={'移除照片 '+(i+1)} onClick={()=>setValue('photos',photos.filter((_,n)=>n!==i),{shouldDirty:true})}><X size={13}/></button>{i===0&&<small>主图</small>}</div>)}{photos.length<12&&(isNativeApp()?<><button type="button" className="upload-box" disabled={saving||uploading} onClick={()=>chooseNativePhoto('camera')}><Camera size={22}/><span>拍照</span></button><button type="button" className="upload-box" disabled={saving||uploading} onClick={()=>chooseNativePhoto('photos')}><Upload size={22}/><span>从相册选择</span></button>{uploading&&<span role="status" className="field-note"><Loader2 className="spin" size={16}/>正在读取照片…</span>}</>:<label className="upload-box">{uploading?<Loader2 className="spin"/>:<Upload size={22}/>}<span>{uploading?'上传中…':'添加照片'}</span><small>JPG / PNG / WebP</small><input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={uploading} onChange={e=>upload(e.target.files)}/></label>)}</div></section>
 <section className="form-section"><h3><span>02</span>商品基本资料</h3><div className="form-grid"><label className="form-field"><span>中文品名</span><Input {...register('nameZh')} placeholder="例如：害羞腮红兔"/></label><label className="form-field"><span>英文品名</span><Input {...register('nameEn')} placeholder="例如：Bashful Blush Bunny"/></label><label className="form-field"><span>商品分类</span><Controller name="category" control={control} render={({field})=><Picker label="商品分类" value={field.value} onChange={field.onChange} items={['公仔','挂件','其他'].map(v=>({value:v,label:v}))}/>}/></label></div><p className="field-note"><Info size={14}/>官方资料按货号保存在下方分支中；同一货号的不同品相共用官方资料。</p></section>
 <section className="form-section"><div className="section-heading"><h3><span>03</span>尺寸与品相分支</h3><Button type="button" variant="outline" onClick={()=>{commitSkuEditing();append(blankVariant());}}><Plus size={15}/>添加分支</Button></div>{fields.map((f,i)=>{const v=variants[i];const skuField=register(`variants.${i}.sku`);const cost=v?costRange(v.purchasePrice,v.targetLow,v.targetHigh):null;return <div className="variant-editor" key={f.id}><div className="variant-heading"><strong>分支 {String(i+1).padStart(2,'0')}</strong>{fields.length>1&&<button type="button" className="icon-btn" aria-label={'删除分支 '+(i+1)} onClick={()=>removeBranch(i)}><Trash2 size={15}/></button>}</div><div className="form-grid three"><label className="form-field"><span>官方货号</span><Input {...skuField} onFocus={()=>beginSkuEditing(i)} onChange={e=>{beginSkuEditing(i);void skuField.onChange(e);}} onBlur={e=>{void skuField.onBlur(e);commitSkuEditing();}} placeholder="例如 BAS3B"/></label><label className="form-field"><span>尺寸 / 规格</span><Input {...register(`variants.${i}.size`)} placeholder="例如 Medium · 31 cm"/></label><label className="form-field"><span>货物品相</span><Controller control={control} name={`variants.${i}.condition`} render={({field})=><Picker label={'分支 '+(i+1)+' 品相'} value={field.value||'unknown'} onChange={v=>field.onChange(v==='unknown'?'':v)} items={[{value:'unknown',label:'留白 · 待确认'},...CONDITIONS.map(c=>({value:c,label:c+' '+CONDITION_LABELS[c]}))]}/>}/></label>{numeric(`variants.${i}.purchasePrice`,'拿货价')}{numeric(`variants.${i}.targetLow`,'目标成交价下限')}{numeric(`variants.${i}.targetHigh`,'目标成交价上限')}</div>{(!v?.sku||variants.findIndex(x=>x.sku.trim().toLowerCase()===v.sku.trim().toLowerCase())===i)?<div className="variant-official"><h4>该货号的官方资料</h4><div className="form-grid"><label className="form-field"><span>官方销售状态</span><Controller control={control} name={`variants.${i}.officialStatus`} render={({field})=><Picker label={'分支 '+(i+1)+' 官方状态'} value={field.value||'unknown'} onChange={x=>field.onChange(x==='unknown'?'':x)} items={[{value:'unknown',label:'留白 · 待确认'},...Object.entries(STATUS_LABELS).map(([value,label])=>({value,label}))]}/>}/></label><label className="form-field"><span>发售时间</span><Input {...register(`variants.${i}.releaseDate`)} placeholder="有可靠依据时填写"/></label>{numeric(`variants.${i}.releasePrice`,'美国首发官方定价')}<label className="form-field"><span>官方资料来源</span><Input {...register(`variants.${i}.sourceUrl`)} type="url" placeholder="https://us.jellycat.com/…"/></label></div></div>:<p className="field-note">官方资料与上方相同货号的分支共用。</p>}<div className="cost-preview"><span>预计成本区间</span><strong>{cost?money(cost.low)+' – '+money(cost.high):'填写拿货价和目标区间后计算'}</strong></div><p className="field-note">拿货价 + $4/件运费 + 成交价 × 16%（平台 11% + 人工 5%）</p></div>;})}</section>
 <section className="form-section"><h3><span>04</span>备注与核实记录</h3><Textarea {...register('notes')} rows={4} placeholder="记录资料来源、待核实信息、商品细节…"/></section></fieldset></div>
 <footer className="editor-actions">{error&&<p role="alert" className="form-error">{error}</p>}<div><span className="muted small-text">所有金额均为美元 USD</span><Button type="submit" className="primary-button" disabled={saving||uploading}>{saving?<Loader2 size={16} className="spin"/>:<Save size={16}/>}确认并保存</Button></div></footer></form></DialogContent></Dialog>;
}
