import type {ImageEmbedder} from '@mediapipe/tasks-vision';
let modelPromise:Promise<ImageEmbedder>|null=null;
const cache=new Map<string,number[]>();
async function model(){if(!modelPromise)modelPromise=(async()=>{const {FilesetResolver,ImageEmbedder}=await import('@mediapipe/tasks-vision');const files=await FilesetResolver.forVisionTasks(new URL('vision/wasm',document.baseURI).href);return ImageEmbedder.createFromOptions(files,{baseOptions:{modelAssetPath:new URL('vision/mobilenet_v3_small.tflite',document.baseURI).href,delegate:'CPU'},runningMode:'IMAGE',l2Normalize:true,quantize:false});})().catch(e=>{modelPromise=null;throw e;});return modelPromise;}
function openCache():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const r=indexedDB.open('jellyshelf-derived-vision-v1',1);r.onupgradeneeded=()=>r.result.createObjectStore('vectors');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function cached(key:string):Promise<number[]|null>{if(cache.has(key))return cache.get(key)!;try{const db=await openCache();return await new Promise((resolve)=>{const r=db.transaction('vectors').objectStore('vectors').get(key);r.onsuccess=()=>{db.close();resolve(r.result??null);};r.onerror=()=>{db.close();resolve(null);};});}catch{return null;}}
async function storeVector(key:string,value:number[]){cache.set(key,value);try{const db=await openCache();const tx=db.transaction('vectors','readwrite');tx.objectStore('vectors').put(value,key);tx.oncomplete=()=>db.close();}catch{}}
async function loadImage(url:string):Promise<HTMLImageElement>{return new Promise((resolve,reject)=>{const image=new Image();if(url.startsWith('https:')||url.startsWith('http:'))image.crossOrigin='anonymous';image.onload=()=>resolve(image);image.onerror=()=>reject(Error('照片无法读取，请选择清晰的 JPG、PNG 或 WebP 图片。'));image.src=url;});}
export async function embedPhoto(url:string,save=false){if(save){const hit=await cached(url);if(hit)return hit;}const engine=await model();const image=await loadImage(url);const max=640;const canvas=document.createElement('canvas');const scale=Math.min(1,max/Math.max(image.naturalWidth,image.naturalHeight));canvas.width=Math.round(image.naturalWidth*scale);canvas.height=Math.round(image.naturalHeight*scale);const context=canvas.getContext('2d')!;context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(image,0,0,canvas.width,canvas.height);const embedding=engine.embed(canvas).embeddings[0].floatEmbedding;if(!embedding)throw Error('无法提取图片特征。');const vector=Array.from(embedding);if(save)await storeVector(url,vector);return vector;}
export function cosine(a:number[],b:number[]){if(a.length!==b.length)return 0;let dot=0,aa=0,bb=0;for(let i=0;i<a.length;i++){dot+=a[i]*b[i];aa+=a[i]*a[i];bb+=b[i]*b[i];}return aa&&bb?dot/Math.sqrt(aa*bb):0;}
