import React, {lazy, Suspense} from 'react';
import {createRoot} from 'react-dom/client';
import CatalogApp from '@/components/catalog-app';
import './globals.css';
import './cream.css';
const PersonalApp=lazy(()=>import('@/components/personal-app'));
const DemoApp=import.meta.env.MODE==='native'?null:lazy(()=>import('@/components/demo-app'));
const params=new URLSearchParams(window.location.search);
const personal=import.meta.env.MODE==='native'||params.get('app')==='1';
const demo=!personal&&params.get('demo')==='1';
createRoot(document.getElementById('root')!).render(<React.StrictMode><Suspense fallback={<div style={{padding:40,textAlign:'center',color:'#8d6747'}} role="status">正在打开软软收藏室…</div>}>{personal?<PersonalApp/>:demo&&DemoApp?<DemoApp/>:<CatalogApp/>}</Suspense></React.StrictMode>);
